backend:
  name: github
  repo: techcarpenter/brianjdevries.com
  branch: main
  squash_merges: true
publish_mode: editorial_workflow
logo_url: https://brianjdevries.com/android-chrome-512x512.png
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: f4c78ae90b2408207f60
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: blog/{{year}}/{{month}}/{{day}}/{{slug}}
    fields:
      - {
          label: "Author",
          name: "author",
          widget: "hidden",
          default: "Brian DeVries"
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          default: "{{now}}",
          picker_utc: true,
          required: true
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          required: true,
        }
  - name: "notes" # Used in routes
    label: "Notes" # Used in the UI
    folder: "src/notes" # The path to the folder where the documents are stored
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}.md" # Filename template
    preview_path: notes
    fields:
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          default: "{{now}}",
          picker_utc: true,
          required: true
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          required: true,
        }
